src/aind_metadata_service/__init__.py, src/aind_metadata_service/sharepoint/client.py, tests/sharepoint/test_client.py
=> adds single quotes to unit test and client

src/aind_metadata_service/__init__.py, src/aind_metadata_service/labtracks/client.py, src/aind_metadata_service/response_handler.py, tests/labtracks/test_client.py
Closes #31
- Adds handler for case where multiple subjects are unexpectedly returned.
- Maps 200 response to common JSONResponse shape as other response types
=> Feat 31 subject response

pyproject.toml, src/aind_metadata_service/__init__.py, tests/test_response_handle.py
=> feat: pins aind-data-schema version

src/aind_metadata_service/sharepoint/client.py, tests/sharepoint/resources/list_item7.json, tests/sharepoint/test_client.py
=> patch: changes experimenter name mapping to NSB-ID

pyproject.toml, src/aind_metadata_service/sharepoint/client.py, tests/sharepoint/test_client.py
=> Feat 65 upgrade schema

.github/workflows/publish.yml
Closes #64 
- Publishes project to pypi so the client can be used
=> ci: publish to pypi

src/aind_metadata_service/client.py, src/aind_metadata_service/response_handler.py
=> moves status codes

src/aind_metadata_service/server.py
Closes #91 
- Enables CORS
- Tested on small javascript snippet
- Is there a need for POST?
=> feat: allows CORS

pyproject.toml, src/aind_metadata_service/client.py, src/aind_metadata_service/server.py, tests/test_client.py
=> Feat 108 Add pickle option

pyproject.toml, src/aind_metadata_service/sharepoint/nsb2023/mapping.py
- Pins office 365 version since the latest version is causing issues
- Also adds a quick check to avoid trying to access value on a None object
=> Feat 107 return model response fix bug

src/aind_metadata_service/client.py, src/aind_metadata_service/response_handler.py, src/aind_metadata_service/server.py, tests/test_client.py, tests/test_response_handler.py
=> feat: implement pickle option

pyproject.toml, src/aind_metadata_service/labtracks/client.py, tests/labtracks/test_response_handler.py
=> negative room or cage

Dockerfile
Pins python version in docker file
=> Hot fix docker file

.github/workflows/ci.yml, pyproject.toml, src/aind_metadata_service/labtracks/client.py, src/aind_metadata_service/server.py, src/aind_metadata_service/sharepoint/nsb2023/mapping.py, src/aind_metadata_service/smartsheet/__init__.py, src/aind_metadata_service/smartsheet/client.py, tests/labtracks/test_response_handler.py, tests/resources/smartsheet/test_sheet.json, tests/smartsheet/__init__.py, tests/smartsheet/test_client.py
Closes #134 
- Adds client to connect to protocols smartsheet data
- Adds test and example smartsheet json response
- Runs linters
- Will join data to procedures later
- Dropped support for python 3.7 since we've been running this on 3.8 and 3.7 doesn't have convenient async classes like unittest.IsolatedAsyncioTestCase
=> Feat 134 smartsheet client

src/aind_metadata_service/response_handler.py, src/aind_metadata_service/tars/client.py, src/aind_metadata_service/tars/mapping.py, tests/resources/tars/mapped_materials.json, tests/tars/test_client.py, tests/tars/test_mapping.py
=> Feat 165 tars mapping

src/aind_metadata_service/server.py, src/aind_metadata_service/sharepoint/client.py, src/aind_metadata_service/smartsheet/client.py, src/aind_metadata_service/smartsheet/funding/mapping.py, src/aind_metadata_service/smartsheet/mapper.py, src/aind_metadata_service/smartsheet/perfusions/mapping.py, tests/smartsheet/test_client.py, tests/smartsheet/test_funding.py, tests/smartsheet/test_perfusions.py
Closes #181 
- Moves call to get sheet out of property, which was downloading the data every time the sheet was referenced
- Updated unit tests
=> feat: moves call to get sheet out of property

.github/workflows/ci.yml, pyproject.toml, src/aind_metadata_service/models.py, src/aind_metadata_service/response_handler.py, src/aind_metadata_service/server.py, src/aind_metadata_service/sharepoint/client.py, src/aind_metadata_service/sharepoint/nsb2023/mapping.py, src/aind_metadata_service/smartsheet/protocols/mapping.py, tests/tars/test_client.py, tests/test_response_handler.py
Closes #186 
- Adds endpoint for a user to query for a bergamo session and input additional, required info
- aind-metadata-mapper requires python>=3.10
=> Feat 186 bergamo session

src/aind_metadata_service/server.py, src/aind_metadata_service/sharepoint/client.py, src/aind_metadata_service/smartsheet/protocols/mapping.py, src/aind_metadata_service/tars/mapping.py, tests/tars/test_mapping.py
closes #195 
Fiber Implant probes is a dictionary on prod. In dev, we receive internal server error due to another bug. This bug is fixed once tars response checks name, not full_genome_name in the injection_materials object from NSB.
=> fix virus strain bug

src/aind_metadata_service/response_handler.py, src/aind_metadata_service/server.py, src/aind_metadata_service/slims/client.py, tests/resources/slims/ephys_rig.json, tests/slims/test_client.py
=> Feat 177 slims rig

src/aind_metadata_service/sharepoint/client.py, src/aind_metadata_service/smartsheet/protocols/mapping.py, src/aind_metadata_service/tars/mapping.py
Fixes issue with list index out of range for empty models
=> fix: fixes index out of range error

Dockerfile
Fixes Dockerfile so server can find index.html file
=> fix: updates dockerfile to locate index.html

src/aind_metadata_service/server.py
=> ci: use single smartsheet api token

src/aind_metadata_service/sharepoint/client.py, src/aind_metadata_service/sharepoint/nsb2023/mapping.py, src/aind_metadata_service/smartsheet/protocols/mapping.py, src/aind_metadata_service/tars/mapping.py, tests/resources/sharepoint/nsb2023/mapped/mapped_list_item10.json, tests/resources/sharepoint/nsb2023/mapped/mapped_list_item22.json, tests/resources/sharepoint/nsb2023/mapped/mapped_list_item9.json, tests/resources/sharepoint/nsb2023/raw/list_item22.json
=> feat: implant part mapping

src/aind_metadata_service/labtracks/client.py, src/aind_metadata_service/server.py, src/aind_metadata_service/sharepoint/client.py, src/aind_metadata_service/smartsheet/protocols/mapping.py, src/aind_metadata_service/tars/mapping.py, tests/labtracks/test_client.py, tests/labtracks/test_response_handler.py
closes #222 
Fixes subject mapping so that it only creates breedingInfo model if atleast one of the values exists. Else, breeding_info=None. If breeding_info, then source is Allen Institute, otherwise Other
some ids to check: 714640, 714650,  999
=> Fixes source mapping

src/aind_metadata_service/client.py, src/aind_metadata_service/response_handler.py, src/aind_metadata_service/server.py, src/aind_metadata_service/slims/client.py, src/aind_metadata_service/slims/models.py, tests/test_response_handler.py
closes #226 
- Updates Slims mappings to look at ReferenceTable for rigs and instruments
- Adds "validate" flag to map_to_json_response 
- rigs and instruments will be returned from SLIMS, will not be validated
- adds handling of KeyErrors, AttributeErrors, and ValueErrors
=> Feat 226 update slims

src/aind_metadata_service/labtracks/client.py, tests/labtracks/test_response_handler.py
=> fix cage id

src/aind_metadata_service/tars/mapping.py, tests/tars/test_mapping.py, tests/test_response_handler.py
=> fix: attribute check for tars injection materials

src/aind_metadata_service/server.py, src/aind_metadata_service/tars/mapping.py, tests/tars/test_mapping.py
hot fix related to issue #233 (already been closed)
=> fix: inj materials check

pyproject.toml
- Adds bergamo dependency from aind-metadata-mapper to support legacy endpoint
=> fix: adds bergamo dependencies for legacy endpoint

pyproject.toml
- Upgrades package dependencies
=> build: upgrades metadata mapper

src/aind_metadata_service/sharepoint/las2020/models.py, src/aind_metadata_service/sharepoint/nsb2019/mapping.py, src/aind_metadata_service/sharepoint/nsb2019/models.py, src/aind_metadata_service/sharepoint/nsb2023/mapping.py, src/aind_metadata_service/sharepoint/nsb2023/models.py, src/aind_metadata_service/sharepoint/utils.py, tests/resources/sharepoint/nsb2023/raw/list_item8.json, tests/sharepoint/las2020/test_mapping.py, tests/sharepoint/las2020/test_models.py, tests/sharepoint/test_client.py, tests/sharepoint/test_utils.py
Closes #262 
- Uses a ValidationWrapper to convert inputs to an Enum field to None if not a valid input
=> Fix 262 optional enum

.github/workflows/publish_dev.yml, .github/workflows/publish_main.yml, .github/workflows/run_dev_tests.yml, .github/workflows/run_main_tests.yml
Closes #264
- Adds github actions to support dev/release/main workflows
=> build: dev and main workflows

src/aind_metadata_service/__init__.py, src/aind_metadata_service/smartsheet/funding/mapping.py, tests/resources/smartsheet/test_funding_sheet2.json, tests/smartsheet/test_funding.py
Closes #266 
- Check org abbreviation when requesting funding info
=> fix: updates bug with funding

src/aind_metadata_service/__init__.py, src/aind_metadata_service/server.py, src/aind_metadata_service/slims/client.py, src/aind_metadata_service/smartsheet/funding/mapping.py, tests/resources/smartsheet/test_funding_sheet.json, tests/slims/test_client.py
Closes #296 
- Patches issue with parsing funding information
=> release v0.15.1

pyproject.toml, tests/resources/slims/mapped/ecephys_session.json, tests/resources/slims/mapped/ecephys_session2.json
Closes #299 
- Updates pydantic and aind-data-schema versions to the latest
=> build: update core package versions

src/aind_metadata_service/server.py, tests/smartsheet/test_funding.py
Closes #317 
- Fixes an issue where a variable was being overwritten downstream
=> fix: updates subject endpoint

src/aind_metadata_service/response_handler.py, src/aind_metadata_service/smartsheet/protocols/mapping.py, src/aind_metadata_service/tars/mapping.py, tests/smartsheet/test_protocols.py, tests/tars/test_mapping.py
Closes #321 
- Adds checks for procedures attribute.
- Replaces a print statement with a logging command
=> fix: adds check for procedures attribute

src/aind_metadata_service/slims/procedures/mapping.py, src/aind_metadata_service/smartsheet/funding/mapping.py, tests/smartsheet/test_funding.py
- Supports legacy project_name inputs
=> fix: support legacy project_names

src/aind_metadata_service/__init__.py, src/aind_metadata_service/tars/mapping.py, tests/tars/test_mapping.py
- Patches bug with constructing viral materials when missing name field
=> release-v0.19.1

README.md, docker-compose.yaml, pyproject.toml, src/aind_metadata_service/backends/slims/__init__.py, src/aind_metadata_service/backends/slims/configs.py, src/aind_metadata_service/backends/slims/handler.py, src/aind_metadata_service/backends/slims/models.py, src/aind_metadata_service/backends/slims/session.py, src/aind_metadata_service/routers/instrument/__init__.py, src/aind_metadata_service/routers/instrument/route.py, src/aind_metadata_service/routers/project_names/route.py, src/aind_metadata_service/routers/rig/__init__.py, src/aind_metadata_service/routers/rig/route.py, src/aind_metadata_service/server.py, tests/backends/slims/__init__.py, tests/backends/slims/test_configs.py, tests/backends/slims/test_handler.py, tests/backends/slims/test_models.py, tests/backends/slims/test_session.py, tests/backends/tars/test_handler.py, tests/routers/instrument/__init__.py, tests/routers/instrument/test_route.py, tests/routers/rig/__init__.py, tests/routers/rig/test_route.py
Closes #336
- Refactors slims endpoint for rig and instrument
- Updates docker compose for latest version of docker
=> feat: adds slims rig and instrument endpoints

src/aind_metadata_service/slims/imaging/handler.py
- Fixes small bug in dev that was filtering incorrect subject_ids in the new smartspim endpoint
=> fix: removes early break to fix subject_id filter

src/aind_metadata_service/sharepoint/client.py
- Adds paginator
- Filters by retro-orbital injections
=> fix: adds paginator

src/aind_metadata_service/server.py, src/aind_metadata_service/slims/client.py, src/aind_metadata_service/slims/water_restriction/__init__.py, src/aind_metadata_service/slims/water_restriction/handler.py, src/aind_metadata_service/slims/water_restriction/mapping.py, tests/resources/slims/water_restriction/content.json, tests/resources/slims/water_restriction/content_event.json, tests/resources/slims/water_restriction/slims_wr_data.json, tests/slims/test_client.py, tests/slims/water_restriction/__init__.py, tests/slims/water_restriction/test_handler.py, tests/slims/water_restriction/test_mapping.py
closes #281 
This PR:
- creates an endpoint slims/water_restriction that returns water restriction data from SLIMS Content Events. Takes optional queries for start date, end date, and subject id
- integrates data from SLIMS into procedures
=> Feat 281 water restriction

aind-metadata-service-server/pyproject.toml, aind-metadata-service-server/src/aind_metadata_service_server/configs.py, aind-metadata-service-server/src/aind_metadata_service_server/main.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/rig_and_instrument.py, aind-metadata-service-server/src/aind_metadata_service_server/response_handler.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/rig_and_instrument.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/slims.py, aind-metadata-service-server/src/aind_metadata_service_server/sessions.py, aind-metadata-service-server/tests/test_configs.py, aind-metadata-service-server/tests/test_mappers/test_rig_and_instrument.py, aind-metadata-service-server/tests/test_routes/test_rig_and_instrument.py, aind-metadata-service-server/tests/test_routes/test_slims.py, docker-compose.yaml
Closes #415 
- Adds rig and instrument and workflows endpoints
- Filters pydantic serializer warnings
=> Feat 415 slims microservice

aind-metadata-service-server/src/aind_metadata_service_server/main.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/funding.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/perfusion.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/protocol.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/subject.py, aind-metadata-service-server/src/aind_metadata_service_server/models.py, aind-metadata-service-server/src/aind_metadata_service_server/response_handler.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/funding.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/protocol.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/slims.py, aind-metadata-service-server/src/aind_metadata_service_server/sessions.py, aind-metadata-service-server/tests/test_mappers/test_funding.py, aind-metadata-service-server/tests/test_mappers/test_protocol.py, aind-metadata-service-server/tests/test_routes/test_funding.py, aind-metadata-service-server/tests/test_routes/test_rig_and_instrument.py, aind-metadata-service-server/tests/test_routes/test_slims.py, aind-metadata-service-server/tests/test_routes/test_subject.py, docker-compose.yaml
- Simplifies router imports in main
- updates docstring return types to A | None instead of Optional[A]
- Doesn't log full validation errors (on the fence about this)
- Updates ResponseHandler TypeVars
- Updates function signatures in Unit Tests
=> feat: updates mappers

aind-metadata-service-server/src/aind_metadata_service_server/main.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/mgi_allele.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/subject.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/mgi_allele.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/slims.py, aind-metadata-service-server/tests/test_mappers/test_mgi_allele.py, aind-metadata-service-server/tests/test_mappers/test_subject.py, aind-metadata-service-server/tests/test_routes/test_mgi_allele.py
closes #418 
- Adds MGI Route and Mapper
- Updates subject mapper to use mgi mapper
=> Feat: Release MGI

aind-metadata-service-server/src/aind_metadata_service_server/main.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/index.py, aind-metadata-service-server/src/aind_metadata_service_server/templates/index.html, aind-metadata-service-server/tests/test_routes/test_index.py
=> feat: index page with subject and procedures search bars

aind-metadata-service-server/pyproject.toml, aind-metadata-service-server/src/aind_metadata_service_server/main.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/index.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/session_json.py, aind-metadata-service-server/src/aind_metadata_service_server/sessions.py, aind-metadata-service-server/tests/test_routes/test_session_json.py, docker-compose.yaml
- Adds endpoint to return a bergamo session.json info
- Fixes Jinja Template deprecation warning
=> feat: adds bergamo session endpoint

.github/workflows/run_dev_server_tests.yml, aind-metadata-service-server/README.md
- Fixes github action to run tests and pull requests to the dev branch
- Updates a comment in the README
=> fix: github actions

aind-metadata-service-server/src/aind_metadata_service_server/routes/funding.py, aind-metadata-service-server/tests/test_routes/test_funding.py
- Returns expected response format
=> fix: project names

aind-metadata-service-server/src/aind_metadata_service_server/models.py, aind-metadata-service-server/tests/test_models.py
- Maps protocol_id field in imaging response
=> fix: updates slims response

aind-metadata-service-server/src/aind_metadata_service_server/mappers/funding.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/funding.py, aind-metadata-service-server/tests/test_mappers/test_funding.py
- Fixes a bug where the funding endpoint wasn't backwards compatible. Users input the information as a single string that needs to split into a project and subproject.
=> fix: makes funding route backwards compatible

aind-metadata-service-server/src/aind_metadata_service_server/__init__.py, aind-metadata-service-server/src/aind_metadata_service_server/mappers/nsb2023.py
Closes #501 
- Patches issue when probe coordinates are `None`
=> release v1.1.5

aind-metadata-service-server/README.md, aind-metadata-service-server/src/aind_metadata_service_server/routes/v1_proxy.py
=> fix: corrects /funding/{project_name} docstring and clarifies local Docker setup

aind-metadata-service-server/src/aind_metadata_service_server/routes/v1_proxy.py, aind-metadata-service-server/tests/test_routes/test_v1_proxy.py
=> fix: Fixes bug causing proxy slims endpoint to stringify None values

aind-metadata-service-server/pyproject.toml, aind-metadata-service-server/src/aind_metadata_service_server/mappers/funding.py, aind-metadata-service-server/tests/test_mappers/test_funding.py, docker-compose.yaml
Updates smartsheet client image and dependencies in v1
=> fix: fix smartsheet missing fundees bug in v1

aind-metadata-service-server/src/aind_metadata_service_server/__init__.py, aind-metadata-service-server/src/aind_metadata_service_server/routes/subject.py, aind-metadata-service-server/tests/test_routes/test_subject.py
closes #550 
Adds MGI back to v1
=> fix: adds mgi back v1

aind-metadata-service-server/src/aind_metadata_service_server/routes/subject.py, aind-metadata-service-server/tests/test_routes/test_subject.py
closes #550 
Adds MGI back for v2 subject endpoint
=> Fix 550 mgi on
