AllenNeuralDynamics/aind-metadata-service

Dockerfile
README.md
doc_template/source/conf.py
pyproject.toml
src/aind_metadata_service/client.py
tests/test_client.py

Closes #35 
- Creates the framework for a client to interface with the service.
- Instead of using curl or requests, can be invoked like
- Can add more detailed handlers in the future
```
from aind_metadata_service.client import AindMetadataServiceClient
ams_client = AindMetadataServiceClient("http://location_of_service")
response = ams_client.get_subject("12345")
```

Feat 35 client library

---

pyproject.toml

Closes #74
- Moves aind-data-schema to server dependency list
- It isn't needed by the client and may cause dependency conflicts for projects that use the client and aind-data-schema

build: moves aind-data-schema to server list

---

src/aind_metadata_service/labtracks/client.py
src/aind_metadata_service/response_handler.py
src/aind_metadata_service/sharepoint/client.py
tests/labtracks/test_client.py
tests/sharepoint/test_client.py
tests/test_response_handler.py

Closes #98 
- Wraps get methods with try clauses. Logs error and returns Internal ServerError Response
- Should hopefully prevent the service from crashing on non-fatal exceptions
- updates the unit tests
- fixes a relative import

Refactor 98 try except

---

src/aind_metadata_service/labtracks/client.py
src/aind_metadata_service/server.py
src/aind_metadata_service/sharepoint/client.py
tests/labtracks/test_client.py
tests/sharepoint/test_client.py

Closes #19 
- Uses pydantic BaseSettings to define labtracks and sharepoint configs
- Can be pulled automatically from env vars
- Handles passing of sharepoint list titles better
- Adds unit tests
- TODO: Add favicon as a static asset?

Feat 19 load configs

---

src/aind_metadata_service/response_handler.py
src/aind_metadata_service/tars/client.py
src/aind_metadata_service/tars/mapping.py
tests/resources/tars/mapped_materials.json
tests/tars/test_client.py
tests/tars/test_mapping.py

closes #171 
Refactors the TARS client and mapping to integrate responses from viral prep lot and molecular registry in TARS into InjectionMaterials. Also defines a model ViralPrepAliases for mapping of aliases in TARS (instead of tuple)

Feat 171 molecule tars

---

doc_template/source/conf.py
pyproject.toml
src/aind_metadata_service/__init__.py
src/aind_metadata_service/client.py
src/aind_metadata_service/labtracks/client.py
src/aind_metadata_service/labtracks/query_builder.py
src/aind_metadata_service/response_handler.py
src/aind_metadata_service/server.py
src/aind_metadata_service/sharepoint/client.py
src/aind_metadata_service/slims/client.py
src/aind_metadata_service/tars/client.py
tests/labtracks/test_response_handler.py
tests/sharepoint/test_client.py
tests/tars/test_client.py
tests/tars/test_mapping.py
tests/test_client.py

closes #166 
- Adds endpoint for injection_materials in the server
- Filters the raw response from TARS to find exact matches (rather than all lots containing input prep lot number)
- Returns no data response when there are no exact matches or if the input is an empty string
- Adds no_data_response class method to ModelResponse
- Pins pydantic version
- black linter updated to add newlines, so there's a couple non-TARS changes in this PR

feat 166: adds tars endpoint

---

src/aind_metadata_service/labtracks/client.py
src/aind_metadata_service/labtracks/query_builder.py
tests/labtracks/test_client.py
tests/labtracks/test_query_builder.py

closes #189
- Added input validation to ensure `subject_id` is alphanumeric with no special characters
- Refactor SQL queries and `cursor.execute()` to use parameterized queries with `?` placeholder to prevent SQL injection attacks
- pyodbc supports parameterized queries ([docs](https://github.com/mkleehammer/pyodbc/wiki/Getting-started#parameters))
- db driver will receive query and params separately and ensures the server does not treat params as part of SQL code
- Updated unit tests as appropriate

Feat 189: Validate `subject_id` and parameterize SQL queries

---

src/aind_metadata_service/server.py
src/aind_metadata_service/templates/index.html

closes #60 
- Added home page `index.html` to be loaded at http://aind-metadata-service/
- Uses Jinja2Template to render with provided context for service (name, description, version) and enabled endpoints (endpoint, description, parameters)
- User can query subjects endpoint by providing a `subject_id` and clicking the "Search" button.
- Query status (including when pending) and response are displayed below. The response is first parsed for status, message, and data.
- The raw response json can also optionally be viewed by clicking the "View raw response" button
----
----
----
----

Feat 60: Add index page and search /subjects UI

---

src/aind_metadata_service/tars/mapping.py
tests/tars/test_mapping.py

closes #205 
Adds checks for Invalid Data and No Data Found for the tars endpoint. 
- If it's invalid, it'll still integrate that data into the procedures response and validate as expected. 
- If the tars endpoint returns a no data found error, it'll pass.

hot fix: tars status handling

---

src/aind_metadata_service/server.py
src/aind_metadata_service/tars/mapping.py
src/aind_metadata_service/templates/index.html

fixes #208 
- remove endpoint label in title 
- use enter to search  
- display data before message

feat: remove endpoint label in title and search with enter

---

src/aind_metadata_service/server.py
src/aind_metadata_service/smartsheet/funding/mapping.py
tests/smartsheet/test_funding.py

Closes #224 
- Adds endpoint to retrieve project names in funding sheet
- Endpoint looks like: `http://aind-metadata-service/project_names`
- Response looks like:
```
{
"message": "Success",
"data": [
"AIND Viral Genetic Tools",
"Behavior Platform",
"Brain Computer Interface",
"Cell Type LUT",
"Cognitive flexibility in patch foraging",
"Discovery-Brain Wide Circuit Dynamics",
"Discovery-Neuromodulator circuit dynamics during foraging",
"Dynamic Routing",
"Ephys Platform",
"Force Foraging",
"Information seeking in partially observable environments",
"Learning mFISH/V1omFISH",
"MSMA Platform",
"Medulla",
"Neurobiology of Action",
"OpenScope",
"Ophys Platform - FP and indicator testing",
"Ophys Platform - SLAP2",
"Single-neuron computations within brain-wide circuits (SCBC)",
"Thalamus in …
```

Feat 224 project names

---

src/aind_metadata_service/server.py
src/aind_metadata_service/sharepoint/las2020/mapping.py
src/aind_metadata_service/sharepoint/las2020/procedures.py
tests/sharepoint/test_client.py

Closes #245 
- Adds pagination to LAS list retrieval
- Adds filter to verify subject id in Title list instead of just a substring of

perf: uses pagination for las

---

src/aind_metadata_service/tars/mapping.py
tests/tars/test_mapping.py

closes #260 
Adds strip to get_virus_strains and in integration method to remove whitespaces, or special characters (such as  "\t") from virus strains pulled from NSB and used to query TARS. Does not handle case sensitive queries in TARS

Fix 260 tars strip

---

src/aind_metadata_service/sharepoint/las2020/mapping.py
src/aind_metadata_service/tars/mapping.py
tests/resources/sharepoint/las2020/mapped/mapped_list_item2.json
tests/resources/sharepoint/las2020/mapped/mapped_list_item3.json
tests/resources/sharepoint/las2020/raw/list_item2.json
tests/resources/sharepoint/las2020/raw/list_item3.json
tests/sharepoint/las2020/test_mapping.py
tests/tars/test_mapping.py

closes #305 
The Internal server error was coming from the tars endpoint trying to retrieve material.name for a Nonetype. While fixing this, I realized that we were returning validation errors because we were returning a str rather than the expected int type for titer
This PR: 
- ensures the material is not a Nonetype before trying to get list of virus strains
- adds parsing for titer str in the mapping of LAS response (previously was returning an invalid return type). Checks scientific notation or str with unit (parses out unit in this case, otherwise default value).
-  If titer from LAS is a Decimal, it will map to none since that probably means user incorrectly input Concentration info. 
- updates examples for coverage purposes

Fix: Handle Viralmaterial Breaks

---

src/aind_metadata_service/smartsheet/funding/mapping.py
tests/smartsheet/test_funding.py

Closes #328
- Project names look like `{project_name} - {subproject_name}` if there is a subproject.
- Funding information requires `{project_name} - {subproject_name}` if there is a subproject.

feat: project names now include subproject names

---

src/aind_metadata_service/server.py
src/aind_metadata_service/slims/client.py
tests/slims/test_client.py

Closes #304 
- Adds option to fetch a rig or instrument by partially matching user input (default is find an exact match)
```
{host}/rig/{rig_id}?partial_match=True
```
- Doesn't do any additional validation check. We may need to update version of aind slims api or snippet to avoid pulling stuff like `323_EPHYS1_OPTO_2024-06-18_tube`

feat: adds bool to allow for partial rig matches

---

src/aind_metadata_service/smartsheet/funding/mapping.py
tests/smartsheet/test_funding.py

- Removes "parent project" from list of acceptable project_names. If a project has a subproject, then a user will need to use the subproject

feat: updates project name list

---

src/aind_metadata_service/models.py
src/aind_metadata_service/tars/client.py
src/aind_metadata_service/tars/mapping.py
tests/tars/test_client.py
tests/tars/test_mapping.py

closes #309 
- Creates model ViralMaterialInformation to allow extra field "stock_titer" to hold Titer data from TARS
- Also updates mappings for Virus identifiers using TARS Virus endpoint
- Stock titer is only available in the TARS endpoint result, the procedures response integrates a ViralMaterial object with titer from NSB

Feat 309: Updates TARS Mappings

---

src/aind_metadata_service/server.py
src/aind_metadata_service/sharepoint/client.py
tests/sharepoint/test_client.py

closes #372 
The NSB 2023 List got split into 2 lists when it was migrated: (1) SWR 2023-Present and (2) SWR 2023-2024 Archive. This PR:
- Adds support for archive list
- Fetches procedures and intended measurements from archive 
- Filters out duplicates (both lists currently contain Surgical requests from 2024)

adds support for nsb 2023-2024 archive list

---

src/aind_metadata_service/tars/client.py
tests/tars/test_client.py

closes #362 
TARS API now supports case-insensitive search. This PR adds a fix to remove case sensitive filtering

fix: case insensitive lot filter

---

src/aind_metadata_service/sharepoint/client.py
src/aind_metadata_service/sharepoint/nsb2023/mapping.py
src/aind_metadata_service/sharepoint/nsb2023/models.py

closes #384 
The NSB Present list had numbers ("Sx-#") in the procedure options. This was apparently a bug, and was removed which caused missing mappings for craniotomies and headframes on our end. This PR adds the new procedure names (without the #s). Left the Sx options in the enum for backwards compatibility.

Fix: Adds updated procedure names

---

src/aind_metadata_service/server.py
src/aind_metadata_service/slims/ecephys/handler.py
src/aind_metadata_service/slims/water_restriction/handler.py
src/aind_metadata_service/slims/water_restriction/mapping.py
src/aind_metadata_service/smartsheet/perfusions/mapping.py
tests/slims/ecephys/test_handler.py
tests/slims/water_restriction/test_handler.py
tests/slims/water_restriction/test_mapping.py
tests/smartsheet/test_perfusions.py

closes #391 
This PR:
- adds method to create procedures model response to perfusion mapper
- integrates perfusions from smartsheet into the procedures response
- adds unit tests
Note:
- only subject_id in the smartsheet is '689418'. you can test http://localhost:5000/procedures/689418 to see the perfusions

feat: integrate perfusions in procedures response

---

src/aind_metadata_service/slims/imaging/handler.py
tests/resources/slims/imaging/content.json
tests/slims/imaging/test_handler.py

closes #401 
Context: The previous implementation made an assumption that the mouse ID will always be the parent ID for a content (since samples are derived from mice). However there are a few cases that the specimen ID is the mouse ID in SLIMS (some whole brains). 
This PR adds a check for if the specimen_id in the parse graph method and adds tests.

fix: adds check on specimen id

---

src/aind_metadata_service/slims/histology/handler.py
src/aind_metadata_service/slims/imaging/handler.py
tests/resources/slims/histology/content.json
tests/resources/slims/imaging/content.json
tests/slims/imaging/test_handler.py

related to #401 
- reverts #402:
- instead of checking the cntn_barCode ("specimen id") and cntn_parentbarCode, which relies on relationships between content in SLIMS, we can check a field "cntn_id" which always represents the labtracks ID.  
- updates subject_id check in histology and smartspim imaging workflows
Note: 
- Saskia mentioned that specimen_id should look like {subject_id}_XXX . That's not represented in SLIMS so I wonder whether we should change the name to something more SLIMS like "barcode"

fix: checks cntn_id for subject_id field

---

aind-metadata-service-server/src/aind_metadata_service_server/models.py
aind-metadata-service-server/src/aind_metadata_service_server/routes/slims.py
aind-metadata-service-server/tests/test_models.py

- Simplifies logic in route
- Uses example.com in unit tests
- Alternatively, a dedicated slims mapper can be used if the mapping becomes complicated

refactor: simplifies route and model

---

aind-metadata-service-server/pyproject.toml
aind-metadata-service-server/src/aind_metadata_service_server/mappers/responses.py
aind-metadata-service-server/src/aind_metadata_service_server/routes/subject.py
aind-metadata-service-server/tests/test_mappers/test_responses.py

- Adds `env` to interrogate ignore list
- Adds method to validate models and return JSONResponses
- Logs validation errors as warnings to server logs
- Adds validation errors to response headers
- Removes response_model in subject endpoint to suppress it from openapi schema.

fix: validates models
